@echo off
setlocal enabledelayedexpansion
REM ========================================
REM Website Blocker Script for Windows 11
REM Generated by Website Blocker Manager
REM ========================================
REM Run as Administrator!

REM Check if running as administrator
net session >nul 2>&1
if %errorLevel% neq 0 (
    echo.
    echo ERROR: Script harus dijalankan sebagai Administrator!
    echo Klik kanan file ini dan pilih "Run as administrator"
    echo.
    pause
    exit /b 1
)

set "HOSTS_FILE=%SystemRoot%\System32\drivers\etc\hosts"
set "BACKUP_FILE=%SystemRoot%\System32\drivers\etc\hosts.backup"
set "LOG_FILE=%~dp0block-websites-log.txt"
set "DOMAIN_COUNT=122"

cls
echo.
echo ========================================
echo  WEBSITE BLOCKER - ACTIVATE MODE
echo ========================================
echo.
echo Domain akan diblokir: !DOMAIN_COUNT!
echo.

REM Validate hosts file exists
if not exist "!HOSTS_FILE!" (
    echo ERROR: Hosts file tidak ditemukan: !HOSTS_FILE!
    echo [%date% %time%] ERROR: Hosts file not found >> "!LOG_FILE!"
    pause
    exit /b 1
)

REM Create backup if not exists
if not exist "!BACKUP_FILE!" (
    echo [%date% %time%] Creating backup... >> "!LOG_FILE!"
    copy "!HOSTS_FILE!" "!BACKUP_FILE!" >nul 2>&1
    if !errorLevel! neq 0 (
        echo ERROR: Backup gagal dibuat. Pastikan Anda punya akses administrator.
        echo [%date% %time%] ERROR: Backup failed >> "!LOG_FILE!"
        pause
        exit /b 1
    )
    echo ✓ Backup berhasil dibuat
) else (
    echo ✓ Backup sudah ada (tidak akan dioverwrite)
)

REM Ask for confirmation
echo.
set /p confirm="Lanjutkan pemblokiran? (Y/N): "
if /i not "!confirm!"=="Y" (
    echo Dibatalkan oleh pengguna.
    echo [%date% %time%] CANCELLED by user >> "!LOG_FILE!"
    pause
    exit /b 0
)

REM Check if domains already blocked
findstr /c:"127.0.0.1 youtube.com" "!HOSTS_FILE!" >nul 2>&1
if !errorLevel! equ 0 (
    echo.
    echo INFORMASI: Domain sepertinya sudah diblokir sebelumnya.
    echo Lanjutkan? (Y/N): 
    set /p reconfirm="Isi Y untuk lanjut, N untuk keluar: "
    if /i not "!reconfirm!"=="Y" (
        echo Dibatalkan.
        pause
        exit /b 0
    )
)

echo.
echo Menambahkan domain ke hosts file...
echo [%date% %time%] Starting block process... >> "!LOG_FILE!"

REM Add domains to hosts file
(
    echo.
    echo # ============================================
    echo # Website Blocker - Added on %date% %time%
    echo # Total domains: !DOMAIN_COUNT!
    echo # ============================================
127.0.0.1 youtube.com
127.0.0.1 www.youtube.com
127.0.0.1 m.youtube.com
127.0.0.1 music.youtube.com
127.0.0.1 studio.youtube.com
127.0.0.1 youtubekids.com
127.0.0.1 spotify.com
127.0.0.1 www.spotify.com
127.0.0.1 open.spotify.com
127.0.0.1 play.spotify.com
127.0.0.1 tiktok.com
127.0.0.1 www.tiktok.com
127.0.0.1 m.tiktok.com
127.0.0.1 vt.tiktok.com
127.0.0.1 instagram.com
127.0.0.1 www.instagram.com
127.0.0.1 m.instagram.com
127.0.0.1 x.com
127.0.0.1 www.x.com
127.0.0.1 twitter.com
127.0.0.1 www.twitter.com
127.0.0.1 shopee.co.id
127.0.0.1 www.shopee.co.id
127.0.0.1 m.shopee.co.id
127.0.0.1 seller.shopee.co.id
127.0.0.1 tokopedia.com
127.0.0.1 www.tokopedia.com
127.0.0.1 m.tokopedia.com
127.0.0.1 seller.tokopedia.com
127.0.0.1 lazada.co.id
127.0.0.1 www.lazada.co.id
127.0.0.1 m.lazada.co.id
127.0.0.1 seller.lazada.co.id
127.0.0.1 blibli.com
127.0.0.1 www.blibli.com
127.0.0.1 m.blibli.com
127.0.0.1 jd.id
127.0.0.1 www.jd.id
127.0.0.1 m.jd.id
127.0.0.1 seller.jd.id
127.0.0.1 bukalapak.com
127.0.0.1 www.bukalapak.com
127.0.0.1 m.bukalapak.com
127.0.0.1 facebook.com
127.0.0.1 www.facebook.com
127.0.0.1 m.facebook.com
127.0.0.1 fb.com
127.0.0.1 www.fb.com
127.0.0.1 reddit.com
127.0.0.1 www.reddit.com
127.0.0.1 m.reddit.com
127.0.0.1 old.reddit.com
127.0.0.1 discord.com
127.0.0.1 www.discord.com
127.0.0.1 canary.discord.com
127.0.0.1 ptb.discord.com
127.0.0.1 web.telegram.org
127.0.0.1 telegram.org
127.0.0.1 www.telegram.org
127.0.0.1 twitch.tv
127.0.0.1 www.twitch.tv
127.0.0.1 m.twitch.tv
127.0.0.1 steampowered.com
127.0.0.1 www.steampowered.com
127.0.0.1 store.steampowered.com
127.0.0.1 community.steampowered.com
127.0.0.1 epicgames.com
127.0.0.1 www.epicgames.com
127.0.0.1 store.epicgames.com
127.0.0.1 roblox.com
127.0.0.1 www.roblox.com
127.0.0.1 m.roblox.com
127.0.0.1 pinterest.com
127.0.0.1 www.pinterest.com
127.0.0.1 pin.it
127.0.0.1 medium.com
127.0.0.1 www.medium.com
127.0.0.1 quora.com
127.0.0.1 www.quora.com
127.0.0.1 m.quora.com
127.0.0.1 linkedin.com
127.0.0.1 www.linkedin.com
127.0.0.1 m.linkedin.com
127.0.0.1 wattpad.com
127.0.0.1 www.wattpad.com
127.0.0.1 m.wattpad.com
127.0.0.1 netflix.com
127.0.0.1 www.netflix.com
127.0.0.1 m.netflix.com
127.0.0.1 hulu.com
127.0.0.1 www.hulu.com
127.0.0.1 disneyplus.com
127.0.0.1 www.disneyplus.com
127.0.0.1 primevideo.com
127.0.0.1 www.primevideo.com
127.0.0.1 detik.com
127.0.0.1 www.detik.com
127.0.0.1 news.detik.com
127.0.0.1 m.detik.com
127.0.0.1 kompas.com
127.0.0.1 www.kompas.com
127.0.0.1 tribunnews.com
127.0.0.1 www.tribunnews.com
127.0.0.1 news.tribunnews.com
127.0.0.1 kumparan.com
127.0.0.1 www.kumparan.com
127.0.0.1 liputan6.com
127.0.0.1 www.liputan6.com
127.0.0.1 m.liputan6.com
127.0.0.1 suara.com
127.0.0.1 www.suara.com
127.0.0.1 idntimes.com
127.0.0.1 www.idntimes.com
127.0.0.1 m.idntimes.com
127.0.0.1 okezone.com
127.0.0.1 www.okezone.com
127.0.0.1 m.okezone.com
127.0.0.1 sindonews.com
127.0.0.1 www.sindonews.com
127.0.0.1 m.sindonews.com
127.0.0.1 kapanlagi.com
127.0.0.1 www.kapanlagi.com
    echo.
) >> "!HOSTS_FILE!"

if !errorLevel! neq 0 (
    echo ERROR: Gagal menambahkan domain ke hosts file.
    echo [%date% %time%] ERROR: Failed to append hosts >> "!LOG_FILE!"
    pause
    exit /b 1
)

REM Flush DNS cache
echo.
echo Clearing DNS cache...
ipconfig /flushdns >nul 2>&1

if !errorLevel! equ 0 (
    echo ✓ DNS cache berhasil dikosongkan
) else (
    echo ! Warning: DNS cache flush tidak berhasil (non-critical)
)

REM Clear browser cache (Chrome)
echo.
echo Clearing Chrome cache...
if exist "%LOCALAPPDATA%GoogleChromeUser DataDefaultCache" (
    rmdir /s /q "%LOCALAPPDATA%GoogleChromeUser DataDefaultCache" >nul 2>&1
    mkdir "%LOCALAPPDATA%GoogleChromeUser DataDefaultCache" >nul 2>&1
    echo ✓ Chrome cache berhasil dikosongkan
) else (
    echo ! Chrome tidak terinstal atau cache tidak ditemukan
)

REM Clear browser cache (Edge)
echo.
echo Clearing Edge cache...
if exist "%LOCALAPPDATA%MicrosoftEdgeUser DataDefaultCache" (
    rmdir /s /q "%LOCALAPPDATA%MicrosoftEdgeUser DataDefaultCache" >nul 2>&1
    mkdir "%LOCALAPPDATA%MicrosoftEdgeUser DataDefaultCache" >nul 2>&1
    echo ✓ Edge cache berhasil dikosongkan
) else (
    echo ! Edge tidak terinstal atau cache tidak ditemukan
)

REM Clear Firefox cache
echo.
echo Clearing Firefox cache...
if exist "%APPDATA%MozillaFirefoxProfiles" (
    for /d %%A in ("%APPDATA%MozillaFirefoxProfiles*") do (
        if exist "%%Acache2" (
            rmdir /s /q "%%Acache2" >nul 2>&1
            mkdir "%%Acache2" >nul 2>&1
        )
    )
    echo ✓ Firefox cache berhasil dikosongkan
) else (
    echo ! Firefox tidak terinstal atau cache tidak ditemukan
)

echo.
echo ========================================
echo  SUCCESS!
echo ========================================
echo.
echo ✓ Total 122 domain berhasil diblokir!
echo.
echo Apa yang perlu Anda lakukan sekarang:
echo 1. Restart atau clear cache di browser
echo 2. Gunakan CTRL+F5 untuk force refresh
echo.
echo Untuk membuka blokir, jalankan: unblock-websites.bat
echo.
echo Log file: !LOG_FILE!
echo.
echo [%date% %time%] Block completed successfully >> "!LOG_FILE!"
pause
